backend:
  name: github
  repo: jpegjune/jpegjune-website
  branch: main
  auth_type: implicit # Add this line
  # Ensure base_url is NOT present or is commented out

media_folder: "images/uploads" # Where to store uploaded images
public_folder: "/images/uploads" # How to access uploaded images

collections:
  - name: "settings" # Collection identifier
    label: "Site Settings" # Name in the CMS UI
    files: # We are editing specific files
      - label: "Content Data" # Label for the file in UI
        name: "content" # Internal name reference
        file: "content.json" # Path to the JSON file
        format: "json"
        fields: # Fields within content.json
          # --- Testing Global Settings ---
          - label: "Global Area" # Label for this section
            name: "global" # Matches the 'global' key in content.json
            widget: "object" # It contains nested fields
            fields: # Fields inside the 'global' object
              - { label: "Brand Name", name: "brandName", widget: "string" }
              - { label: "Copyright Year", name: "copyrightYear", widget: "string" }
          # --- Testing Index Settings ---
          - label: "Home Page Area" # Label for this section
            name: "index" # Matches the 'index' key in content.json
            widget: "object"
            fields: # Fields inside the 'index' object
              - { label: "Tagline", name: "tagline", widget: "string" }